config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "items#index"
  resources :sub_categories
  resources :categories
  resources :items do
    get  :search, on: :collection
    post :add_stock, on: :member
    post :remove_stock, on: :member
  end
  
  resources :orders do
    post   :add_item, on: :member
    delete :remove_item, on: :member
    post   :charge_payment, on: :member
  end
  
  resources :users do
    post :create_user, on: :collection 
    get  :user_profile, on: :member
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many  :orders, dependent: :destroy
  validates :name, :email, :address, :phone, presence: true
  validates :email, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #  GET /users/new
  def new
    @user = User.new
      respond_to do |format|
        format.html
      end
  end

  # POST /users
  def create
    @user = User.create!(user_params)
    if @user.valid?
      flash[:notice] = 'successfull created'
      redirect_to users_path
    else
      flash[:notice] = @user.errors.full_messages
      render :new
    end
  end

  # GET /users
  def index
    @users = User.all
    respond_to do |format|
      format.html
    end
  end

  private
  def user_params
    params.require(:user).permit( :name, :email, :password, :address, :phone, :date_of_birth, :gender )
  end
end

app/views/users/_form.html.erb
<div class=" new_user_container container d-flex justify-content-center mt-5">
  <div class="container d-flex justify-content-center">
    <%= form_with url: create_user_users_path(@user), model: @user do |form| %>
      <% if @user.persisted? %>
      <p style="font-weight:bold; color:black; font-size:1.5rem">Edit Profile </p>
      <% else %>
      <p style="font-weight:bold; color:black; font-size:1.5rem">Create New User </p>
      <% end %>
      <div>
        <%= form.label :name, "Name", class:"mt-4" %><br>
        <%= form.text_field :name, class:"text_field form-control no-border" %>
      </div>
      <div>
        <%= form.label :emal, "Email", class:"mt-4"  %><br>
        <%= form.text_field :email, class:"text_field form-control no-border" %>
      </div>
      <div>
        <%= form.label :password, "Password", class:"mt-4" %><br>
        <%= form.text_field :password, class:"text_field form-control no-border" %>
      </div>
      <div>
        <%= form.label :address, "Address", class:"mt-4" %><br>
        <%= form.text_area  :address, class:"text_field form-control no-border" %>
      </div>
      <div>
        <%= form.label :date_of_birth, "Date of Birth", class:"mt-4" %><br>
        <%= form.date_field :date_of_birth, class:"text_field form-control no-border" %>
      </div>
      <div>
        <%= form.label :phone, "Phone", class:"mt-4" %><br>
        <%= form.telephone_field :phone, class:"text_field form-control no-border" %>
      </div>
      <div>
        <%= form.label :gender, "Gender", class:"mt-4" %>
        <%= form.select :gender,[["Male","male"], ["Female","female"]],{}, { :class => "form_select" } %>
      </div>
      <%= form.submit  @user.persisted? ? 'Update' : 'Create', class:"create_user_button mt-5 form-control no-border text-white" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render partial: "form" %>

app/views/users/index.html.erb
<%= link_to "new", new_user_path, class:"btn btn-outline-secondary m-3" %>
<div class="m-3">
  <table class="table table-secondary table-bordered border-secondary">
    <tr>
      <th >#</th>
      <th >Name</th>
      <th >Email</th>
      <th >Gender</th>
      <th >Type</th>
      <th ></th>
    </tr>
    <% @users.each do |user| %>
      <tr >
        <td>
        <%= user.id %>
        </td>
        <td >
          <%= user.name %>
        </td>
        <td >
          <%= user.email %>
        </td>
        <td >
          <%= user.gender %>
        </td>
        <td >
          <%= user.role %>
        </td>
        <td>
          <%= link_to "Edit", edit_user_path(user), class:"btn btn-primary" %>
          <%= link_to "Delete", user_path(user), method: :delete, class:"btn btn-primary" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<%= render partial: "form" %>