config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "items#index"
  resources :sub_categories
  resources :categories
  resources :items do
    get  :search, on: :collection
    post :add_stock, on: :member
    post :remove_stock, on: :member
  end
  
  resources :orders do
    post   :add_item, on: :member
    delete :remove_item, on: :member
    post   :charge_payment, on: :member
  end
  
  resources :users do
    post :create_user, on: :collection 
    get  :user_profile, on: :member
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many   :order_items, dependent: :destroy
  has_many   :payments, dependent: :destroy
  belongs_to :user, class_name: 'User', foreign_key: 'customer_id'
  validates  :customer_id, presence: true
  # validates  :discount_percentage, numericality: { greater_than_or_equal_to: 0, less_than_equal_to: 100}
  
  def recalculate_total_price
    total_price = order_items.map{|order_item| order_item.price * order_item.quantity}.sum
    self.update(total_price: total_price)
  end

  def recalculate_paid_amount
    calculated_paid_amount = payments.sum(:paid_amount)
    self.update(paid_amount: calculated_paid_amount)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :load_order, only: [  :show, :remove_item, :charge_payment, :add_item ]
  
  # GET /orders/new
  def new
    @order = Order.new
    respond_to do |format|
      format.html
    end
  end

  # POST /orders
  def create
    @order = Order.create!( customer_id: current_user.id, state: "cart" )
    if @order.valid?
      flash[:alert] = 'successfull Created'
      redirect_to order_path(@order)
    else
      flash[:notice] = @order.errors.full_messages
      render :new  
    end
  end

  # GET /orders
  def index
    @orders = policy_scope(Order)
    respond_to do |format|
      format.html
    end
  end
  
  # GET /orders/:id 
  def show
    authorize(@order)
    @order_items = @order.order_items
    respond_to do |format|
      format.html
    end
  end

  # POST /orders/:id/add_item 
  def add_item
    valid = true
    begin
      ActiveRecord::Base.transaction do
        item_id = params.dig(:items, '0')
        order_id = params["id"]
        item = Item.find(item_id)
        item_price = item.price
        @order_item = OrderItem.create!(item_id: item_id, order_id: order_id, price: item_price, quantity: params["quantity"].to_i)
        @order.recalculate_total_price
      end
    rescue ActiveRecord::RecordInvalid => e
      valid = false
      errors = [e.message]
    end
    if valid
      flash[:message] = 'Item successfully added'
      redirect_to order_path(@order)
    else
      flash[:notice] = errors
      render :show
    end
  end

  # Delete /orders/:id
  def remove_item
    @order_item = OrderItem.find(params[:order_item_id])
    @order_item.destroy!
    if @order_item.destroyed?
      flash[:notice] = 'successfully Deleted'
      @order.recalculate_total_price
      redirect_to order_path(@order)
    else
      flash[:errors] = @order.errors.full_messages
      redirect_to order_path(@order)
    end
    
  end

  # POST /orders
  def charge_payment
    valid = true
    begin
      ActiveRecord::Base.transaction do
        @payment = Payment.create(order_id: params[:id], paid_amount: params[:paid_amount])
        @order.recalculate_paid_amount
      end
    rescue ActiveRecord::RecordInvalid => e
      valid = false
      errors = [e.message]      
    end

    if valid
      flash[:notice] = 'Payment successfull'
      redirect_to order_path(@order)
    else
      flash[:errors] = errors
      render :show 
    end
  end
  private

  def load_order
    @order = Order.find(params[:id])
  end
end

app/views/orders/index.html.erb
<%= link_to "Create Order", orders_path, method: :post, class:"btn btn-outline-secondary m-2" %>
<table class="table table-bordered border-secondary table-secondary">
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Total Price</th>
    <th>Discount Percentage</th>
    <th>Discounted value</th>
    <th>Total Discount</th>
    <th>State</th>
    <th>Date & Time</th>
  </tr>
  <tr>
    <% @orders.each do |order| %>
      <td>
        <%= order.id %>
      </td>
      <td>
        <%= order.user.name %>
      </td>
      <td> 
        <%= order.total_price %>
      </td>
      <td>
        <%= order.discount_percentage %>
      </td>
      <td>
        <%= order.discounted_value %>
      </td>
      <td>
        <%= order.total_discount %>
      </td>
      <td>
        <%= order.state %>
      </td>
      <td>
        <%= order.created_at %>
      </td>
    </tr>
  <% end %>
</table>

app/views/orders/show.html.erb
<!-- for user(customer) -->
<div class="add_item_container container d-flex justify-content-center mt-3 mb-3 rounded-2">
  <div class="field_bar container d-flex justify-content-center ">
    <%= form_with url: add_item_order_path(@order) do |form| %>
      <span>
        Search Item
        <div class="search_container mb-3 ">
          <input type="text" name="search" id="js-search">
        </div>
      </span>
      <%= javascript_tag do %>
        var tf = new Tokenfield({
          el: document.querySelector('#js-search'),
          remote: {
            url: "/items/search.json",
          }
        });
      <% end %>
      <%= form.label :quantity, "Quantity" %>
      <%= form.number_field :quantity, class:"text_field form-control no-border" %>
      <div class="conatainer d-flex justify-content-center mt-3">
      <%= form.submit "Add", class:"btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>
<div class="m-2">
  <table class="table table-bordered table-secondary ">
      <tr >
        <th >Item</th>
        <th >Price</th>
        <th >Quantity</th>
        <th></th>
      </tr>
    <% @order_items.each do |order_item| %>
      <tr >
        <td >
          <%= order_item.item.name %>
        </td>
        <td >
          <%= order_item.price %>
        </td>
        <td >
          <%=  order_item.quantity %>
        </td>
        <td >
          <%= link_to "Cancel", remove_item_order_path(@order, order_item_id: order_item.id), method: :delete, class: "btn btn-primary" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<!-- for admin only -->
<button type="button" class="btn btn-primary ms-2" data-bs-toggle="modal" data-bs-target="#paymentModal">
  Charge Amount
</button>

<!-- Modal -->
<div class="modal fade" id="paymentModal" tabindex="-1" aria-labelledby="paymentModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="paymentModalLabel">Balance</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body d-flex justify-content-center">
        <div class="payment_container container d-flex justify-content-center rounded-2"> 
        <div class="container d-flex justify-content-center"> 
        <%= form_with url: charge_payment_order_path(@order) do |form| %>
          <% if current_user.admin? || current_user.owner?%>
            <div>
            <%= form.label :paid_amount, "Amount", class:"mt-3 text-black" %><br>
            <%= form.number_field :paid_amount, class:"text_field rounded-1 form-control no-border"%>
            <% end %>
            </div>
            <div class="mt-3">
            <%= form.label :total_price, "Total amount : ", class:"text-black" %> 
            <%= @order.total_price %>
            </div>
            <div class="mt-2">
            <%= form.label :paid_amount, "Paid :", class:"text-black mt-2" %>
            <%= @order.paid_amount %>
            </div>
            <div class="mt-2">
            <%= form.label :paid_amount, "Remaining : ", class:"text-black" %>
            <%= (@order.total_price).to_i  - (@order.paid_amount).to_i %>
            </div>
            <% if current_user.admin? || current_user.owner? %>
            <div class=" mt-4">
            </div>
          <% end %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancle</button>
        <%= form.submit "Pay", class:"btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>








<%# modal of payment history %>
</div>
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#paymenthistoryModal">
    Payment History
  </button>
<div>

<!-- Modal -->
<div class="modal fade" id="paymenthistoryModal" tabindex="-1" aria-labelledby="paymenthistoryModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="paymenthistoryModalLabel">Payment History</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class = "table table_size">
          <tr class >
            <th >Amount</th>
            <th >Paid On</th>
          </tr>
          <% @order.payments.each do |payment| %>
            <tr >
              <td  >
                $<%= payment.paid_amount %> --
              </td>
              <td >
                <%= payment.created_at %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>