config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "items#index"
  resources :sub_categories
  resources :categories
  resources :items do
    get  :search, on: :collection
    post :add_stock, on: :member
    post :remove_stock, on: :member
  end
  
  resources :orders do
    post   :add_item, on: :member
    delete :remove_item, on: :member
    post   :charge_payment, on: :member
  end
  
  resources :users do
    post :create_user, on: :collection 
    get  :user_profile, on: :member
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :sub_category
  has_many   :order_items, dependent: :restrict_with_error
  has_many   :line_items, dependent: :destroy
  validates  :name, :category_id, :sub_category_id, presence: true
  validates  :quantity, numericality: { greater_than_or_equal_to: 0 }
  validates  :price, numericality: { greater_than_or_equal_to: 0 }

  after_initialize :init

  def init
    self.quantity ||= 0.0
  end
  
  def recalculate_current_quantity! 
    item_quantity = line_items.pluck(:quantity).sum
    self.update!(quantity: item_quantity)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :load_item, only: [ :show, :edit, :update, :destroy, :add_stock, :remove_stock ]

  # GET /items
  def index
    @items = Item.all.includes(:category, :sub_category)
    respond_to do |format|
      format.html
    end
  end

  # GET /items/new
  def new
    @item = Item.new
    authorize(@item)
    load_data_for_form
    respond_to do |format|
      format.html
    end
  end

  # POST /items
  def create
    valid = true
    begin
      ActiveRecord::Base.transaction do 
        @item = Item.new(item_params)
        @item.quantity = 0
        @item.save!
        @line_item = LineItem.create!(quantity: params.dig(:item, :quantity), item_id:@item.id)
        @item.recalculate_current_quantity!
      end
    rescue ActiveRecord::RecordInvalid => e
      valid = false
      errors = [e.message]
    end
    if valid
      flash[:notice] = 'Item has been created!'
      redirect_to item_path(@item)
    else
      load_data_for_form
      flash[:error] = errors
      render :new
    end
  end

  # GET /items/:id
  def show
    @line_items = @item.line_items 
    respond_to do |format|
      format.html
    end
  end

  # POST /items/:id
  def add_stock
    valid = true
    begin
      ActiveRecord::Base.transaction do 
        LineItem.create!(quantity: params[:quantity], item_id: @item.id)
        @item.recalculate_current_quantity!
      end
    rescue ActiveRecord::RecordInvalid => e
    valid = false
    errors = [e.message]
    end

    if valid
      flash[:notice] = 'stock has been added'
      redirect_to items_path
    else
      flash[:errors] = errors
      redirect_to items_path
    end
  end

  #  POST /items/:id
  def remove_stock
    valid = true
    begin
      ActiveRecord::Base.transaction do
        item_quantity = params[:quantity].to_i * -1
        LineItem.create!(quantity: item_quantity, item_id: params[:id])
        @item.recalculate_current_quantity!
      end
    rescue ActiveRecord::RecordInvalid => e
      valid = false
      errors = [e.message]    
    end

    if valid
      flash[:notice] = 'stock has been removed'
      redirect_to items_path
    else
      flash[:notice] = errors
      render :show
    end
  end

  # GET /items/:id/edit
  def edit
    authorize(@item)
    load_data_for_form
  end

  # PATCH/PUT /items/:id
  def update
    @item.update!(item_params)
    if @item.valid?
      flash[:notice] = 'Item has been Updated'
      redirect_to items_path
    else
      load_data_for_form
      flash[:notice] = @item.errors.full_messages
      render :edit
    end
  end

  # DELETE /items/:id
  def destroy  
    authorize(@item)
    @item.destroy
    if @item.destroyed?
      flash[:notice] = 'Item successfully Deleted'
      redirect_to items_path
    else
      flash[:errors] = @item.errors.full_messages
      redirect_to items_path
    end
  end

  # GET /items/search
  def search
    params_str = params[:q] 
    filtered_items = Item.where('name LIKE ?', "%#{params_str}%")
    filtered_items = filtered_items.collect { |item| {id: item.id, name: item.name } }
    respond_to do |format|
      format.json do
        render json: filtered_items, status: :ok
      end
    end
  end

  private
 
  def load_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit( :name, :price, :sub_category_id, :category_id )
  end  

  def load_data_for_form
    @categories = Category.all
    @sub_categories = SubCategory.all
  end
end

app/views/items/_form.html.erb
<div class="new_item_container container d-flex justify-content-center mt-3 border-black">
  <div class="container d-flex justify-content-center mt-3">
    <%= form_with model: @item do |form| %>
      <div>
        <%= form.label :name, "Item name", class:"mt-3" %>
        <%= form.text_field :name, class:"text_field form-control no border" %>
      </div>
      <div>
        <%= form.label :quantity, "Quantity", class:"mt-3" %>
        <%= form.number_field :quantity, class:"text_field form-control no border" %>
      </div>
      <div>
        <%= form.label :price, "Price", class:"mt-3" %>
        <%= form.number_field :price, class:"text_field form-control no border" %>
      </div>
      <div>
        <%= form.label :sub_category_id, "Subcategory", class:"mt-4" %>
        <%= form.select(:sub_category_id, options_for_select(@sub_categories.map { |sub_category|
        [sub_category.title, sub_category.id]  } ),{}, {:class => 'select_options '})%>
      </div>
      <div>
        <%= form.label :category_id, "Category ", class:"mt-4" %>
        <%= form.select(:category_id, options_for_select(@categories.map { |category|
        [category.title, category.id] }),{}, {:class => 'select_options'}) %>
      </div>
      <div class="mt-3">
        <%= form.submit @item.persisted? ? 'Update' : 'Create', class:"new_item_button rounded-2 form-control no-border" %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<%= render partial: "form" %>

app/views/items/index.html.erb
<%if user_signed_in? %>
<% if current_user.admin? || current_user.owner?%>
<%= link_to "New", new_item_path, class:"btn btn-outline-secondary m-3" %> 
<% end%>
<% end %>
<%# cards of items %>
<% @items.each do |item| %>
  <div class="card m-3" style="width: 18rem;">
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"> <%= item.name %> </h5>
    Quantity : <%= item.quantity %><br>
    Price : <%= item.price %><br>
    SubCategory : <%= item.sub_category.title %><br>
    Categpory :<%= item.category.title %><br>
    <%= link_to "Show", item_path(item), class:"btn btn-primary" %>
    <% if user_signed_in? %>
    <% if current_user.admin? || current_user.owner? %>
      <%= link_to "Edit", edit_item_path(item), class:"btn btn-primary" %>
      <%= link_to "Delete", item_path(item), method: :delete, class:"btn btn-primary" %>
    <% end %>
    <% end %>
    </div>
  </div>  
<% end %>

app/views/items/new.html.erb
<%= render partial: "form" %>

app/views/items/show.html.erb
<%# card of Item  %>
<div class="card m-3" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">  <%= @item.name %> </h5>
    <div class="mt-3">
      <%= label_tag 'price', 'Price : ' %>
      <%= @item.price %>
    </div>
    <div class="mt-3">
      <%= label_tag 'quantity', 'Qunatity : ' %>
      <%= @item.quantity %>
      </div>
    <div class="mt-3">
      <%=label_tag 'sub_category_title', 'Sub category : ' %> 
      <%= @item.sub_category.title %>
    </div>
    <div class="mt-3">
      <%= label_tag 'category_title', 'Category : '  %>
      <%= @item.category.title %>
    </div>
  </div>
</div>

<%# add stock modal  %>
<% if current_user.admin? || current_user.owner? %>
  <button type="button" class="btn btn-primary ms-2" data-bs-toggle="modal" data-bs-target="#addstockModal">
    Add Stock
  </button>
  <div class="modal fade" id="addstockModal" tabindex="-1" aria-labelledby="addstockModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addstockModalLabel">Add stock</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= form_with url: add_stock_item_path(@item) do |form| %>
          <div class="modal-body d-flex justify-content-center">
            <%= form.label :quantity, "Quantity" %>
            <%= form.number_field :quantity, class:"text_field form-control no-border" %>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancle</button>
          <%= form.submit "Add", class:"btn btn-primary" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>



  <%# modal %>
  <button type="button" class="btn btn-primary ms-2" data-bs-toggle="modal" data-bs-target="#removestockModal">
    Remove Stock
  </button>
  <div class="modal fade" id="removestockModal" tabindex="-1" aria-labelledby="removestockModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="removestockModalLabel">Remove stock</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= form_with url: remove_stock_item_path(@item) do |form| %>
          <div class="modal-body d-flex justify-content-center">
            <%= form.label :quantity, "Quantity" %>
            <%= form.number_field :quantity, class:"text_field form-control no-border" %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancle</button>
            <%= form.submit "remove", class:"btn btn-primary" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>