config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "items#index"
  resources :sub_categories
  resources :categories
  resources :items do
    get  :search, on: :collection
    post :add_stock, on: :member
    post :remove_stock, on: :member
  end
  
  resources :orders do
    post   :add_item, on: :member
    delete :remove_item, on: :member
    post   :charge_payment, on: :member
  end
  
  resources :users do
    post :create_user, on: :collection 
    get  :user_profile, on: :member
  end
end

app/views/layouts/_flash_messages.html.erb
<% if flash.present? %>
  <div>
    <% if flash[:error].present? %>
      <% if flash[:error].is_a?(Array) %>
        <% flash[:error].each do |error_message| %>
          <div>
            <%= error_message %>
          <div>
        <% end %>
      <% else %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:error] %>
        </div>
      <% end %>
    <% elsif flash[:alert].present? %>
      <% if flash[:alert].is_a?(Array) %>
        <% flash[:alert].each do |error_message| %>
          <div class="alert" role="alert">
            <%= error_message %>
          <div>
        <% end %>
      <% else %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong><%= flash[:alert] %></strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag('/token_input') %>
  <title>Cash2Deals</title>
</head>
<body>
  <nav class="navbar">
    <%= link_to "Cash2Deals", root_path, class: 'navbar_logo  btn' %>
        <ul class="ul">
      <% if user_signed_in?%>
        <% if current_user.owner? || current_user.admin?  %>
        <li class="ul_item">
          <%= link_to "User", users_path, class: 'navbar_logo btn btn-light' %>
        </li>
          <li class="ul_item">
          <%= link_to "Categories", categories_path, class: 'navbar_logo btn btn-light' %>
          </li>
          <li class="ul_item">
          <%= link_to "SubCategory", sub_categories_path, class: 'navbar_logo btn btn-light' %>
          </li>
        <% end %>
      <% end %>
      <li class="ul_item">
    <%= link_to "Order", orders_path, class: 'navbar_logo btn btn-light' %>
    </li>
    <li class="ul_item">
    <% if user_signed_in? %>
      <%= link_to "profile", edit_user_path(current_user), class: 'navbar_logo btn btn-light' %>
    <% end %>
    </li>
    <li class="ul_item">
     <% if user_signed_in? %>
       <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'navbar_logo btn btn-light' %>
       <%= current_user.name %>
     <% end %>
     </li>
     </ul>
    </nav>
  <%= render partial: '/layouts/flash_messages' %>
  <%= yield %>
</body>
</html>